### ISSUE TITLE
R891 configuration

### ISSUE THREAD

**Issue by jlysiak** [gavanderhoorn/packet-fanuc-hspo-r891#1]
Hi @gavanderhoorn 
I appreciate your work. I would like to test R891 in simulation.
Two questions.
1. Could you shed a light on how to configure that R891 beastie? I've spent a lot of time trying to learn anything on the Internet.
2. Do you have any data about the output rate?  

Thanks in advance!

**Comment by gavanderhoorn** [comment]
> 1\. Could you shed a light on how to configure that R891 beastie? I've spent a lot of time trying to learn anything on the Internet.

Could you clarify whether you've already asked Fanuc for the documentation? There are relatively few system variables which you'd need to configure, and everything is explained in the documentation.

> 2\. Do you have any data about the output rate?

Maximum rate for `R891` is 500 Hz. But Fanuc recommends to keep the size of the output packets low in that case, as otherwise the available processing power could become a problem.

Finally:

> I would like to test R891 in simulation.

Afaik, `R891` will not work in current versions of Roboguide.

Last time I discussed this with them they mentioned only the variable part of it works, but not the joint/Cartesian state broadcast.

**Comment by gavanderhoorn** [comment]
As this is not an issue with the dissector, I'm going to close it.

Feel free to keep commenting on the issue of course.
